name: json_compare_bench
description: Cross-language JSON serialization benchmarks
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.6.0
  codable:
    path: /usr/local/google/home/kevmoo/github/kevmoo/_codable.dart-sdk-integration/pkgs/codable

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
